version: "0.2"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: comot
    path: ""
    text-resources:
      - path: src/locale/*.xlf
        format: angular-hardcoded
